defaults:
  - _self_
  - model: gpt35
  - sampling: top_p_sampling
  - aggregation: majority_vote
  - prompt: few_shot_cot
  - reasoning_algorithm: normal_reasoning
  - dataset: gsm8k
  - task: gsm8k

experiment:
  experiment_name: "self_consistency_gsm8k_small_test"
  seed: 42

hydra:
  run:
    dir: "log/${experiment.experiment_name}/${now:%Y-%m-%d_%H-%M-%S}"
  sweep:
    dir: "log/${experiment.experiment_name}/${now:%Y-%m-%d_%H-%M-%S}/multirun"
    subdir: "${hydra.job.num}"